### ISSUE TITLE
Consider splitting this library into modular parts. 

### ISSUE THREAD

**Issue by ARitz-Cracker** [bitjson/bitcoin-ts#14]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Personally I'm never going to use the wasm Sha functions as both the web browser and NodeJS provide native implementations of that. Perhaps you should put secp256k1 in a different package `secp256k1-wasm` or something like that for all the other parts and make `bitcoin-ts` depend on all the parts.

**Comment by bitjson** [comment]
Hey @ARitz-Cracker, thanks for opening an issue! I'm definitely considering also publishing some component pieces of this library as smaller node modules, especially once #9 lands.

One upside of the monorepo approach is that we avoid forcing projects to rely on NPM's somewhat-insecure dependency resolution to wire up the library. E.g. this module already works in [Deno](https://github.com/denoland/deno).

Does [Rollup](https://rollupjs.org) work for your use case? No matter how this library is modularized, breaking code into small packages will always be less precise than a real tree-shaking/live-code inclusion option. In the case of Secp256k1, you can even use [`instantiateSecp256k1Bytes`](https://bitjson.github.io/bitcoin-ts/globals.html#instantiatesecp256k1bytes) to load the WASM manually without including the base64 encoded string in your bundle.

(As an aside, I just wanted to mention that the WASM SHA implementations [are actually superior to native in most cases](https://blog.bitjson.com/just-released-sha-256-sha-512-sha-1-and-ripemd-160-using-webassembly-6179275330c0), and getting even faster as engines improve WASM performance. 😄)

**Comment by ARitz-Cracker** [comment]
Hello! Thanks for your response. Informative as always. And yeah, it's 100% true that I don't have to pack everything when distributing my thing for end-users, and `instantiateSecp256k1Bytes` does enable me to get the WASM executable from an AJAX request or a file read.

Also, I didn't know that the WASM SHA implementations perform better than `SubtleCrypto`. That's pretty neat!

I'll go ahead and close this issue, now. I really appreciate that someone went ahead made an _actually decent way_ to use `secp256k1` without having a billion dependencies.
