### ISSUE TITLE
Export tweakAdd and tweakMul for public & private key

### ISSUE THREAD

**Issue by andkom** [bitjson/bitcoin-ts#15]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Need this methods to fast calculate incrementing key pair.

**Comment by ARitz-Cracker** [comment]
Oh hi! I already did this.

**Comment by andkom** [comment]
@bitjson 
@ARitz-Cracker did tests in his PR #17
