### ISSUE TITLE
Add memory leak testing with leakage

### ISSUE THREAD

**Issue by bitjson** [bitjson/bitcoin-ts#2]
After https://github.com/andywer/leakage/pull/27 lands

**Comment by junderw** [comment]
It was merged.

**Comment by bitjson** [comment]
After a little more consideration here, I don't think it's relevant for this library. 

Since the exposed functionality is all written in a purely-functional style, and linting is preventing us from inadvertently bloating the global namespace or modifying built-in features, there really should be no way for this library to (itself) leak memory. The real leaks are going to happen downstream in consumers, if anywhere. (If you're using TypeScript and modern tooling, it's still unlikely.)

If anyone finds this in the future, I'd probably accept a PR that adds a separate `test:leakage` script like the `bench` script, but I'm going to close this for now.
