### ISSUE TITLE
Is it possible to have a blocking instantiateSecp256k1? 

### ISSUE THREAD

**Issue by madeken** [bitjson/bitcoin-ts#20]
I'm trying to use bitcoin-ts inside my (synchronous) library, but it's a bit clumsy to use due to the async nature of instantiateSecp256k1 and (AFACIT) will force my functions to also become async (or loading the library async). I'm not quite sure how the webassembly stuff works, but I'm wording if it's possible to have a blocking version?

**Comment by ARitz-Cracker** [comment]
Your functions do not have to be async, you'll just have to load it async.
Unfortunately, there doesn't appear to be a way to start up WASM binaries synchronously. As [WebAssembly.instantiate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate) will always return a promise.

**Comment by madeken** [comment]
Thought so! Thanks for the reply.
